In [4]:
%load_ext autoreload
%autoreload 2
import pandas as pd
import numpy as np
from settings import WEEKS_DICT, STUDENT_EMAILS

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [13]:
labs_table = pd.read_csv(r"C:\Users\crocs\OneDrive - Universidade de Lisboa\Ambiente de Trabalho\Gonçalo\Jobs\Ironhack-TA\labs-control\data\students_performance.csv")
macro_table = pd.read_csv(r"C:\Users\crocs\OneDrive - Universidade de Lisboa\Ambiente de Trabalho\Gonçalo\Jobs\Ironhack-TA\labs-control\data\macro_status.csv")

In [15]:
macro_table.head(25)

,Unnamed: 0,student_name,student_image_url,completed_required_labs,total_required_labs,completion_pctg
0,0,Adrian Flores,https://ih-public-production-student-card.s3-e...,25,34,0.74
1,1,Aferdita Zherka Zherka,/static/media/default_user_picture.7ea4af7d.png,16,34,0.47
2,2,Alicia Andrés,https://ih-public-production-student-card.s3-e...,22,34,0.65
3,3,Amelie Haberland,https://ih-public-production-student-card.s3-e...,21,34,0.62
4,4,Angela Arredondo Mendoza,https://ih-public-production-student-card.s3-e...,24,34,0.71
5,5,Damiano Serra,https://ih-public-production-student-card.s3-e...,25,34,0.74
6,6,Daniel J Mendez Borges,https://ih-public-production-student-card.s3-e...,17,34,0.50
7,7,Fabio Blank Da Costa,/static/media/default_user_picture.7ea4af7d.png,25,34,0.74
8,8,Federico Cavanagh,https://ih-public-production-student-card.s3-e...,25,34,0.74
9,9,Francisco Javier De Las Heras Jimenez,/static/media/default_user_picture.7ea4af7d.png,25,34,0.74
10,10,Gregor Seegers,/static/media/default_user_picture.7ea4af7d.png,26,34,0.76
11,11,Joaquin Valentin,https://ih-public-production-student-card.s3-e...,26,34,0.76
12,12,Manouk Meilof,/static/media/default_user_picture.7ea4af7d.png,8,34,0.24
13,13,Marc Gavaldà,/static/media/default_user_picture.7ea4af7d.png,26,34,0.76
14,14,María Vázquez Casares,https://ih-public-production-student-card.s3-e...,23,34,0.68
15,15,Max Grempel,/static/media/default_user_picture.7ea4af7d.png,20,34,0.59
16,16,Shilei Tan Tan,/static/media/default_user_picture.7ea4af7d.png,27,34,0.79
17,17,Suparna Mandal,https://ih-public-production-student-card.s3-e...,25,34,0.74
18,18,Vanessa Andrade,https://ih-public-production-student-card.s3-e...,7,34,0.21
19,19,Óscar Iglesias Roqueiro,https://ih-public-production-student-card.s3-e...,27,34,0.79

In [6]:

weeks_df = pd.DataFrame.from_dict(WEEKS_DICT, orient='index').stack().reset_index()
weeks_df.columns = ['Week', 'row', 'Lab_name']
weeks_df = weeks_df.drop('row', axis=1)

In [7]:
weeks_df.head()

     Week                    Lab_name
0  Week 1                 Lab Strings
1  Week 1     Lab Dicts, sets, tuples
2  Week 1                   Lab Lists
3  Week 1                     Lab Git
4  Week 2  Lab DataFrame Calculations

In [8]:
tabled_merge = labs_table.merge(weeks_df, how="left", left_on = "lab", right_on = "Lab_name" )

In [12]:
tabled_merge.loc[tabled_merge["Week"] <= "Week "+ str(12)]["lab_status"].value_counts()

Delivered    202
Pending       78
Name: lab_status, dtype: int64

In [16]:
tabled_merge

,Unnamed: 0,student_name,lab,required,lab_status,submission_date,Week,Lab_name
0,0,Adrian Flores,Lab Git,Required,Delivered,07/09/2022,Week 1,Lab Git
1,1,Adrian Flores,Lab Lists,Required,Delivered,09/09/2022,Week 1,Lab Lists
2,2,Adrian Flores,"Lab Dicts, sets, tuples",Required,Delivered,10/09/2022,Week 1,"Lab Dicts, sets, tuples"
3,3,Adrian Flores,Lab Strings,Required,Delivered,14/09/2022,Week 1,Lab Strings
4,4,Adrian Flores,Lab Intro to pandas,Required,Delivered,17/09/2022,Week 2,Lab Intro to pandas
...,...,...,...,...,...,...,...,...
855,37,Óscar Iglesias Roqueiro,Lab Imbalance,Required,Pending,NaN,Week 19,Lab Imbalance
856,38,Óscar Iglesias Roqueiro,Lab Problems in ML,Required,Pending,NaN,Week 21,Lab Problems in ML
857,39,Óscar Iglesias Roqueiro,Lab Unsupervised Learning,Required,Pending,NaN,Week 21,Lab Unsupervised Learning
858,40,Óscar Iglesias Roqueiro,Lab Deep Learning,Required,Pending,NaN,Week 22,Lab Deep Learning
859,41,Óscar Iglesias Roqueiro,Lab NLP,Required,Pending,NaN,Week 22,Lab NLP

In [ ]:
student_names = tabled_merge["student_name"].unique().tolist()


for student in student_names:
    
    # filtering by student
    student_sub = tabled_merge[tabled_merge["student_name"] == student]
    
    # count delivered and not delivered labs
    delivered_labs = (
        tabled_merge[tabled_merge["lab_status"]== "Delivered"]["Lab_name"]
        .unique()
        .tolist()
    )
    pending_labs =(
        tabled_merge[tabled_merge["lab_status"]== "Pending"]["Lab_name"]
        .unique()
        .tolist()
    )
    
    # add as strings lines
    delivered_labs_strings = "\n".join(delivered_labs)
    pending_labs_strings = "\n".join(pending_labs)
    
    # calculate the percentage of delivered labs
    lab_percent = round((delivered / (delivered+not_delivered))*100)

In [37]:
def send_emails(
    labs_overall : pd.DataFrame,
    week_number_email : int,
    email_sender : str,
    email_password: str, 
    email_dict : dict = STUDENT_EMAILS
    ) -> str:

    student_names = list(email_dict.keys())


    for student in student_names:
        
        # Filtering by student
        student_sub = labs_overall[labs_overall["student_name"] == student]
        
        # Filtering by week number
        student_sub_week = student_sub[student_sub["week_num"] <= week_number_email]
        
        # Count delivered and not delivered labs
        submissions = student_sub_week["lab_status"].value_counts()
        delivered = submissions["Delivered"]
        try:
            not_delivered = submissions[""]
        except:
            not_delivered = 0
        
        # Get the lab names of non delivered ones
        pending_labs = student_sub_week[student_sub_week["lab_status"] == ""]["lab_name"].values.tolist()
        pending_labs_strings = "\n".join(pending_labs)
        
        # Calculate the percentage of delivered labs
        lab_percent = round((delivered / (delivered+not_delivered))*100)
                            
        if lab_percent < 80:
            body = f'''Dear {student.split()[0]}, we have been checking your lab sumissions status. From a total of {delivered + not_delivered} labs, you have submitted {delivered}, this represents the {lab_percent}% of the total until now.
    Remember that ironhack rules mark 80% as the threshold to complete the course. Don't hesitate in contacting us if you need help to meet that threshold. We will be happy to support you!

    The labs that you are missing are:
    {pending_labs_strings}
            
    Ironhack Teaching Team
            '''
                            
        elif lab_percent == 100:
            body = f'''Dear {student.split()[0]}, we have been checking your lab sumissions status. From a total of {delivered + not_delivered} labs, you have submitted {delivered}, this represents the {lab_percent}% of the total until now.
    You have submitted all the labs so far, so congratulations for this hard job!
            
    Ironhack Teaching Team
            '''
        
        else:
            body = f'''Dear {student.split()[0]}, we have been checking your lab sumissions status. From a total of {delivered + not_delivered} labs, you have submitted {delivered}, this represents the {lab_percent}% of the total until now.
    You are over the 80% threshold marked by Ironhack to complete the course so congratulations! You are properly following the course progress.
    Anyway,there are some labs that are still missing:
    {pending_labs_strings}

    Keep going with the hard job!
            
    Ironhack Teaching Team
            '''
        #later replace with : email_dict[student]:    
        email_receiver = "miguelsimonmoya@gmail.com" 
        
        subject = "Ironhack lab status"
        
        em = EmailMessage()
        em["From"] = email_sender
        em["To"] = email_receiver
        em["subject"] = subject
        em.set_content(body)

        context = ssl.create_default_context()

        with smtplib.SMTP_SSL("smtp.gmail.com", context = context) as smtp:
            smtp.login(email_sender, email_password)
            smtp.sendmail(email_sender, email_receiver, em.as_string())
        
                            
        time.sleep(2)
    
    return "E-mails sent to all students. Repeat proccess next week (:"

['Lab Confidence Intervals',
 'Lab Pandas Deep-dive',
 'Lab Parallelization | Optional']

In [1]:
import pathlib
SECRETS_PATH =  pathlib.Path().resolve().parents[0] / 'secrets'

with open(SECRETS_PATH.joinpath('secrets.txt')) as f:
    secrets = f.read().splitlines()

In [ ]:
pathlib.Path().resolve().parents[0] / 'life_expectancy/data'